### ISSUE TITLE
lock locks screen then takes a screenshot?

### ISSUE THREAD

**Issue by initzx** [meskarune/i3lock-fancy#101]
I've been having a problem with using scrot to take the screenshot for the lock screen background. It seems as if the screenshot is taken after the screen is turned off? And thereby making the lock screen background entirely black when i wake up the computer. Though this problem does not happen if i manually suspend the laptop by shutting the lid of it. I've put the following command under my i3 config:
`exec_always xautolock -detectsleep -time 5 -locker '/usr/local/bin/lock -gpt "some text"'`

**Comment by AladW** [comment]
"Wake up the computer"? How did you lock the screen beforehand? By waiting until the 5 minutes set in xautolock expires? For the "shutting the lid part", do you further use some systemd service or script that calls i3lock?

**Comment by meskarune** [comment]
Hello @initzx, are you still experiencing issues using i3lock-fancy? I have a similar setup to you, using xautolock with i3lock-fancy. Is it possible you could do some further debugging? If you no longer need assistance with this maybe you could close the issue.
