### ISSUE TITLE
Script filename could be better

### ISSUE THREAD

**Issue by ng-0** [meskarune/i3lock-fancy#103]
I'm currently renaming the 'lock' script to 'i3lock-fancy' in /bin/ in the install phase of the package.

In my opinion this makes more sense than lock. Lock is very generic. It resembles the function "Now I want to *lock* the screen!" but it's not a unique namespace.
i3lock-fancy would fit into the i3lock-\* space.

What do you think? Any other ideas?

**Comment by AladW** [comment]
Duplicate of #81. With a makefile, you can easily install it to wherever you want, e.g. make PROGNM=i3lock-fancy install.
