### ISSUE TITLE
switching to tty 2 still possible, upstream bug/non-goal?

### ISSUE THREAD

**Issue by ng-0** [meskarune/i3lock-fancy#104]
Is it a bug or non-goal in i3lock or i3lock-color that you can still switch to for example tty 2 with a key combination?

I've used screen lockers that really lock the screen and prevent such behavior, so I'm irritated that this is possible with i3lock based screen lockers.

**Comment by AladW** [comment]
I have no idea why you're filing this bug to i3lock-fancy, which is a simple wrapper around i3lock itself.

https://www.jwz.org/xscreensaver/faq.html#no-ctl-alt-bs

See physlock, sflock, etc.

**Comment by PandorasFox** [comment]
I was actually poking around yesterday and it seems there might be a way (with signals) to log out the current user of other TTYs when i3lock is run (though it can't really do anything about other users).

However, implementing it is unreliable and not really worth the effort. You'd be better off putting that in your lock script.

**Comment by ng-0** [comment]
Simple: I wasn't sure at which of the 2 upstreams (first level? second level?) to open a bug, so I hoped someone with enough insight would provide a reply to this question. So, thanks @PandorasFox and @AladW
