### ISSUE TITLE
--textcolor is an invalid arg now

### ISSUE THREAD

**Issue by PandorasFox** [meskarune/i3lock-fancy#109]
I had to refactor a bunch of stuff in i3lock-color, and one of the results of that is that --textcolor is deprecated since it doesn't serve a purpose anymore.

There's `--verifcolor` and `--wrongcolor` now in its place (and colors for the other strings, like the kb modifier string/keylayout string/etc)

I may just go back and add `--textcolor` back in and just warn on it instead of it warning as an unrecognized option, if this is a problem.

(Sorry about that, it was becoming a pretty big/unmaintainable mess, so I didn't really have any good choice other than to break some backwards compatibility when I introduced some new stuff/cleaned it all up 😢 )

**Comment by meskarune** [comment]
Thanks so much for updating us! I really need to sit down and refactor and update.

**Comment by meskarune** [comment]
fix is merged in
