### ISSUE TITLE
Liberation fonts missing

### ISSUE THREAD

**Issue by insanebits** [meskarune/i3lock-fancy#11]
when lauched from terminal I get folowing:
`convert.im6: unable to read font `Liberation-Sans' @ warning/annotate.c/RenderType/853.`

When I run `fc-list | grep "Liberation-Sans"` it doesn't find anything but with `fc-list | grep "Liberation Sans"`  i get folowing results:

    /usr/share/fonts/truetype/liberation/LiberationSansNarrow-Italic.ttf: Liberation Sans Narrow:style=Italic
    /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf: Liberation Sans:style=Regular
    /usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf: Liberation Sans Narrow:style=Regular
    /usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf: Liberation Sans:style=Italic
    /usr/share/fonts/truetype/liberation/LiberationSansNarrow-BoldItalic.ttf: Liberation Sans Narrow:style=Bold Italic
    /usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf: Liberation Sans:style=Bold Italic
    /usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf: Liberation Sans Narrow:style=Bold
    /usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf: Liberation Sans:style=Bold

So the problem seems that ubuntu doesn't have Liberation-Sans font and uses Liberation Sans

**Comment by meskarune** [comment]
Perhaps I should change the font to one that is more standard across linux distrobutions? Anyone has some suggestions?

**Comment by pid1** [comment]
Could we simply respect whatever the user has configured as their sans-serif default, instead of hard-coding a specific font?

**Comment by meskarune** [comment]
Oh, thats a good idea @pid1 I think I can grab the default font with:

    fc-match sans-serif

On my system I get:

    NotoSans-Regular.ttf,: "Noto Sans" "Regular"

**Comment by meskarune** [comment]
Ok, turns out image magic doesn't use font config for fonts and instead has a file called type.xml where it has a list of fonts it can use. @insanebits 

Can you run the following:

    convert -list font | grep Liberation

If liberation fonts aren't listed you may need to add them to type.xml. You can create a type.xml file with this script: http://www.imagemagick.org/Usage/scripts/imagick_type_gen

Honestly though I am considering just using Dejavu Sans since it is installed by default on most Linux distro's.

**Comment by meskarune** [comment]
Ok, after some more playing around I came up with this to find the default sans font and then grep it from image magick's list:

    convert -list font| grep -m 1 -B 1 "family: $(fc-match sans -f "%{family}\n")"

I'm not sure if this will work in all instances, but I'll continue to play around with this.

**Comment by meskarune** [comment]
Ok, the script now uses the default sans system font but you can edit it to use any font that you like. I'm gonna close. Thanks y'all.
