### ISSUE TITLE
Conky on i3lock

### ISSUE THREAD

**Issue by mateuszlewko** [meskarune/i3lock-fancy#110]
Would it be possible to run conky (or polybar) on top of i3lock?

**Comment by PandorasFox** [comment]
you _might_ be able to set stuff up with a compositor to get it working. I know that in some DEs/WMs, Chrome notifications will draw over i3lock (unless you use some really iffy compositor grabbing/hacking), so it's definitely possible to get *some* stuff drawn over

**Comment by AladW** [comment]
Not an `i3lock-fancy` issue.
