### ISSUE TITLE
LeakSanitizer: detected memory leaks

### ISSUE THREAD

**Issue by mattconway1984** [meskarune/i3lock-fancy#114]
Runs ok, but after unlocking there is a memory leak reported:

    ================================================================
    ==17979==ERROR: LeakSanitizer: detected memory leaks

    Direct leak of 8294400 byte(s) in 1 object(s) allocated from:
        #0 0x7fd40ddc3ce1 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:70
        #1 0x55defbebaf15  (/usr/bin/i3lock+0x2df15)
        #2 0x55defbea41a3  (/usr/bin/i3lock+0x171a3)
        #3 0x7fd40b549f49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)

    SUMMARY: AddressSanitizer: 8294400 byte(s) leaked in 1 allocation(s).

**Comment by mattconway1984** [comment]
The script I used to execute I3 lock when this leak was reported:

`
#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ff00ffcc'  # default
T='#ee00eeee'  # text
W='#880000bb'  # wrong
V='#bb00bbbb'  # verifying

i3lock -i /home/mconway/.config/lockscreen.jpg -t \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 1            \
--blur 5              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
--keylayout 2         \

# --veriftext="Drinking verification can..."
# --wrongtext="Nope!"
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc
`

**Comment by PandorasFox** [comment]
https://github.com/PandorasFox/i3lock-color/issues/88

this is actually an issue with fontconfig that I'm investigating. The recent fontconfig 2.13 release broke a bunch of stuff.

Why are you using a debug build of i3lock-color?

**Comment by mattconway1984** [comment]
I'm using i3lock-color from the AUR:

    [mconway@kingpin ~]$ yaourt -Q i3lock-color 
    local/i3lock-color 2.11-3

So whoever built it must have built the debug build.

**Comment by mattconway1984** [comment]
Sorry; I have just realised I've posted this issue on the wrong i3-lock repo, will log it on the right one now.

**Comment by mattconway1984** [comment]
Thanks, I'll switch over to i3lock-color-git
