### ISSUE TITLE
convert: non-conforming drawing primitive definition

### ISSUE THREAD

**Issue by hringriin** [meskarune/i3lock-fancy#115]
```
convert: non-conforming drawing primitive definition `path' @ error/draw.c/DrawImage/4126
```

Using `i3lock-fancy-dualmonitors-git` from the Arch User Repository, downgrading imagemagick and libmagick to `7.0.7.28-1` quick-fixes that problem.

Maybe that [Stackoverflow][stack] article is of use, but probably not.

[stack]: https://stackoverflow.com/questions/48498392/imagemagick-non-conforming-drawing-primitive-definition-matte-error-draw-c-d "Stackoverflow"

**Comment by einfachtorben** [comment]
thanks that downgrading helped!

**Comment by LinuCC** [comment]
Same error message was referenced in https://github.com/ImageMagick/ImageMagick/issues/974 , with the answer being:

> The  internal ImageMagick SVG renderer is not fully compliant with the  specification.  Instead we recommend you build ImageMagick with an  alternative renderer, libRSVG, or inkscape.

**Comment by rinfiyks** [comment]
The latest version of {image,lib}magick (7.0.7.34-1) fixes this issue. No longer a need to downgrade :)

**Comment by hringriin** [comment]
Nice, thanks for the information! :+1:
