### ISSUE TITLE
Mac OSX or Windows Support

### ISSUE THREAD

**Issue by Cortlandd** [meskarune/i3lock-fancy#121]
Could this work on Mac or Windows?

**Comment by PandorasFox** [comment]
No. i3lock-color depends heavily on Linux libs/userspace and the X window system (or at least, screen locking through X) does not exist on OS X or Windows.

**Comment by meskarune** [comment]
Sorry @Cortlandd the script has primarily Linux software dependencies so it's not possible for the locker to work in windows or OSX. I don't think there is a version of i3lock that works on any other OS and that is a hard dependency of i3lock-fancy. However, LInux is free to download and free to use, so there is nothing stopping you from installing it and trying it out! You can dual boot with whatever OS you like best. Thanks for your interest in this project.

**Comment by AladW** [comment]
Technically you can run i3 using XQuartz or Cygwin, respectively. That's widely out of scope for this project, though.
