### ISSUE TITLE
Don't unecessarily call convert when user specifies explicit font

### ISSUE THREAD

**Issue by Boruch-Baum** [meskarune/i3lock-fancy#131]
Our versions have diverged too much for me to mention this as a pull request, sooo ...

You're currently always calling ```convert```/```fc-match```/```awk``` to define a font, even when the user will later over-ride that by using the ```-f``` option. See my commit 5cf646c on my master branch

**Comment by AladW** [comment]
So if you don't specify `-f`, it runs `convert -font ""` - how does that work out?

**Comment by AladW** [comment]
I asked a simple question and all you can come up is with a personal attack. Suit yourself.
