### ISSUE TITLE
i3lock-fancy is incompatible with Wayland

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [meskarune/i3lock-fancy#136]
*** Bug ***
- i3lock-fancy is incompatible with Wayland

*** log ***
```

user@computer  ~/Dokumente/git/i3lock-fancy   master  /usr/bin/i3lock-fancy 
import: unable to read X window image `root': Resource temporarily unavailable @ error/xwindow.c/XImportImage/4979.
import: missing an image filename `/tmp/tmp.6X1Olsb8ZU.png' @ error/import.c/ImportImageCommand/1289.
```

**Comment by PandorasFox** [comment]
honestly pretty expected; i3lock doesn't work with wayland either....

**Comment by cRaZy-bisCuiT** [comment]
Well, maybe it's time to rebuild i3lock-fancy based on swaylock? Or do you think that would be a new tool swaylock-fancy insteadt? ;)

**Comment by exastion** [comment]
For me it works, but you need `grim`.
```
i3lock-fancy -- grim
```

**Comment by PandorasFox** [comment]
> Well, maybe it's time to rebuild i3lock-fancy based on swaylock? Or do you think that would be a new tool swaylock-fancy insteadt? ;)

swaylock already supports most of the color options that i3lock-color does, so there's nothing else that's needed, honestly.

> For me it works, but you need grim.

If it's still using `i3lock` then it might be popping up an X window and then drawing on that, which is (very) insecure. You might want to double check that by switching to another tty when your machine is locked then and just looking at what processes are running - if you have an Xorg process, then it's not actually really using i3lock.

All that should be needed is swaylock + grim

**Comment by AladW** [comment]
If you use Wayland, it's as simple as adding a local commit changing `i3lock` to `swaylock` (or whatever tool you prefer).
