### ISSUE TITLE
No fork options doen't work

### ISSUE THREAD

**Issue by squiter** [meskarune/i3lock-fancy#144]
I was trying to use the `-n` option for `i3lock` in `i3lock-fancy` to use in a helper script but it doesn't work.

```
#!/bin/bash
killall compton
i3lock-fancy -npg
compton
```

I want to kill compton before run the `i3lock-fancy` but this script only work with `i3lock`.

**Comment by iAmG-r00t** [comment]
@squiter why don't you run this script as your lock mechanism, I have noticed the tool has been changed the older options are not there so you should just create a script for locking then execute it with your bind key.

**Comment by AladW** [comment]
"doesn't work" doesn't say anything. The script otherwise passes on the `-n` parameter to i3lock{,-color} and both projects still support this parameter.
