### ISSUE TITLE
i3lock-fancy doesn't work with newest scrot

### ISSUE THREAD

**Issue by lisuml** [meskarune/i3lock-fancy#150]
Since upgrading scrot from 0.9.1.1 to 1.1.1.1, i3lock-fancy, when ran with scrot command, throws the following error:

```
$ i3lock-fancy --nofork -p -- scrot
convert: improper image header `/tmp/tmp.geDncHrd6j.png' @ error/png.c/ReadPNGImage/4293.
convert: no images defined `txt:-' @ error/convert.c/ConvertImageCommand/3273.
```
Downgrading scrot to 0.9.1.1 fixed the issue.

**Comment by shiroyk** [comment]
In scrot stable 1.0 version, by default do not overwrite the file.
You can add option -o to overwrite file.

`i3lock-fancy -p -- scrot -z -o`

**Comment by oryband** [comment]
This should probably go to the front README

**Comment by lisuml** [comment]
Thanks, it seems to be working.
