### ISSUE TITLE
Git checkout doesn't work for dualmonitors branch

### ISSUE THREAD

**Issue by gardotd426** [meskarune/i3lock-fancy#152]
Issue: trying to perform the commands given in the instructions doesn't work, dualmonitors branch won't install
Expected Behavior: follow the instructions, install the package
Acutal Behavior: Installation instructions say to cd into the i3lock-fancy folder, then perform a checkout before installing the application. When you try to perform said checkout, you get this: "error: pathspec 'i3lock-fancy-dualmonitors' did not match any file(s) known to git"
Please fix this.

**Comment by rinfiyks** [comment]
The readme has a typo, you want `git checkout dualmonitors`

**Comment by sim590** [comment]
Shouldn't this issue be closed?
