### ISSUE TITLE
Release time?

### ISSUE THREAD

**Issue by JulienPalard** [meskarune/i3lock-fancy#157]
de145dffe728b9cb67d19addb1daf6a060e34c07 fixed the leak of tmp files, I'll appreciate a lot seeing it land on Debian :)

Thanks a lot for i3lock-fancy, I greatly appreciate it! (I sometime remove the text, lock, a blur, when I'm teaching, so I can lock my machine, go grab a coffee, while my students can still read on the video projector, don't know if we should turn this as a feature or not).

**Comment by AladW** [comment]
Why not cherry-pick https://github.com/meskarune/i3lock-fancy/commit/de145dffe728b9cb67d19addb1daf6a060e34c07 in your package?
