### ISSUE TITLE
There are two "waiting icons" when there are two monitors

### ISSUE THREAD

**Issue by xor512** [meskarune/i3lock-fancy#164]
I have the following setup:

- A laptop with a screwed up screen (mechanical issue, pink stains over the screen, cannot fix)
- A monitor connected to the laptop via VGA-cable due to the screwed up screen in the  laptop

The screen is "doubled", meaninig that for example in arandr  I do not set double-screen settings, but the same image is on both screens (both on a laptop, and a monitor, see the following screenshot: https://raw.githubusercontent.com/xor512/trashbin/master/i3fancy_lock_bug/arandr.png).

The following happens in this setting when i3lock-fancy is launched, which is done in awesome-wm via the following line in rc,lua:

`respawn_with_shell("xautolock", "xautolock -detectsleep -time 10 -notify 30 -notifier \"notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'\" -locker 'i3lock-fancy -g -n' &")`

(see https://github.com/xor512/dotfiles/blob/master/home/ss/.config/awesome/rc.lua):

https://raw.githubusercontent.com/xor512/trashbin/master/i3fancy_lock_bug/i3_double_wait_icon.jpg

As seen in i3_double_wait_icon.jpg there are 2 "waiting icons" instead of 1.

**Comment by AladW** [comment]
Does typing animate both icons? If so, it's most likely an upstream issue in i3lock(-color).

**Comment by xor512** [comment]
Yes, both icons are animated. Also it only happens when both lids are open.

What does it mean upstream? That is going to be fixed? I'm getting i3fancy lock from arch https://aur.archlinux.org/packages/i3lock-fancy-git/ so it is straight from git.

Maybe I need this https://github.com/guimeira/i3lock-fancy-multimonitor?

Can you please clarify? The whole point of "fanciness" is that it is fancy, and two icons instead of one are not fancy.

**Comment by xor512** [comment]
Ah OK I understood, by upstream you mean that the problem is not in the script but in what it wraps. But what about this i3lock-fancy-multimonitor? I haven't tried it yet, will try and tell if the problem is also there - if it is not, that it should be also fixable in original i3lock-fancy, right?

**Comment by xor512** [comment]
Just tried that https://github.com/guimeira/i3lock-fancy-multimonitor and I'm seeing exact same issue. Should I report that to i3lock than?

**Comment by xor512** [comment]
OK I've seen that with original i3lock also. Will report there.

**Comment by xor512** [comment]
Submitted https://github.com/i3/i3/issues/4150.
