### ISSUE TITLE
error while loading shared libraries: libraw_r.so.19

### ISSUE THREAD

**Issue by mdyamin007** [meskarune/i3lock-fancy#167]
It was working fine but after someday it says:
convert: error while loading shared libraries: libraw_r.so.19: cannot open shared object file: No such file or directory
import: error while loading shared libraries: libraw_r.so.19: cannot open shared object file: No such file or directory

What to do? I am Manjaro Linux user.

**Comment by AladW** [comment]
Looks like your imagemagick installation is broken. Ask in your distribution support channels.
