### ISSUE TITLE
Reduce the account lock time on failing for 3 times

### ISSUE THREAD

**Issue by PlankCipher** [meskarune/i3lock-fancy#170]
So, 10 mins is kinda too long to wait to be able to unlock the account. Is there a way to reduce this period?

**Comment by snugglej** [comment]
@PlankCipher I'm a lurker on a lot of github sites, but I saw this and I thought I could help. If you haven't figured this out yet the lockout isn't controlled by this application but by PAM. So you will need to configure your password lockout policy.

https://websistent.com/linux-password-lockout-policy/

**Comment by PlankCipher** [comment]
That was helpful. Thanks a lot.
