### ISSUE TITLE
Flag -d doesn't hid the windows from the screenshot

### ISSUE THREAD

**Issue by snugglej** [meskarune/i3lock-fancy#173]
Hi, 
I'm wondering if -d is supposed to hide the windows and then take a picture of the blank desktop? Right now from reviewing the code the picture occurs prior to the wmctrl -k on command so the picture is showing the windows and whatever contents may be up.

Thanks,

Rich

**Comment by AladW** [comment]
You'd have to do this in a way compatible to all window managers, and correctly such that the user can restore the windows after unlock. PR welcome.
