### ISSUE TITLE
multilingual users

### ISSUE THREAD

**Issue by amixsty** [meskarune/i3lock-fancy#176]
Hi
I useing two diffrent languages . First is English and the second is Persian . I usaly switch between these by `Right ctrl + Shift`
when I'm in Persian i can't type my password currectly because it's set on English charachters.
Solve thist problem by adding these short keys allowed when screen is locked.
thanks

**Comment by AladW** [comment]
> Solve thist problem by adding these short keys allowed when screen is locked.

That's not something that can be done in a wrapper script - it has to be supported directly by `i3lock`. Maybe `i3lock-color` could let you configure which keys to pass through.
