### ISSUE TITLE
Sorry, i'm new to i3, could you tell me how to install it?

### ISSUE THREAD

**Issue by RryLee** [meskarune/i3lock-fancy#18]
I guess need some config to .i3/config

**Comment by meskarune** [comment]
hello. To use the script you can download it and save somewhere in your path. On my computer I have it installed in "/usr/local/bin" essentially you just copy the files there. (lock, lock.png and lockdark.png)

Then in your i3 configuration you can set a keybinding to run the script (/usr/local/bin/lock), or just type "lock" in a terminal. If you want your computer to lock automatically, you can use another program called xautolocker.

Before the script will run you need to have the dependancies installed, specially i3lock-color, scrot and image magick.

Let me know if you have any other questions.

**Comment by RryLee** [comment]
@meskarune  Thank you very much, i am going to try.

Very nIce lookface.
