### ISSUE TITLE
Windows come to foreground when HDMI is unplugged/plugged

### ISSUE THREAD

**Issue by Mohammadreza99A** [meskarune/i3lock-fancy#188]
I use Awesome WM and Arch Linux with my laptop. I have two type of workstations configured in my laptop. Docked and mobile. When HDMI cable is not connected we are in mobile mode and use laptop's screen. When HDMI is connected we go to docked mode and turn off laptop's display and use external display.

If my laptop is locked in mobile mode and than I plug the HDMI cable, we go to docked mode (because of the daemon script) but the problem is that all windows come to foreground and lock screen goes to background (behind all windows). The same thing happens if we go from docked to mobile while the screen is locked. Is there anyway for fix this?

**Comment by johnchristopher** [comment]
Hi,

I ran into the same problem. So I swapped `i3lock` with `slock` and `slock` does cover the screen that is switched on when resuming the laptop. So either it's an `i3lock` problem or it's an `i3lock/awesome` combination problem.

I also tested this:

- monitor on, laptop screen off
- start i3lock
- turn off monitor
- autorandr switches laptop screen on
- desktop is visible (but is frozen/locked, keys can be entered to unlock)

Same sequence bu starting with monitor off and laptop screen on exhibits same behaviour (visible frozen desktop and keys can be entered to unlock).

With `slock` screens are always covered with the locker, whatever the starting conditions are.
