### ISSUE TITLE
i3lock-fancy doesn't work, if I installed from source.

### ISSUE THREAD

**Issue by raaron773** [meskarune/i3lock-fancy#191]
If I run it, I get the following error.
`i3lock-fancy: line 9: convert: command not found`
`i3lock-fancy: line 98: import: command not found`

**Comment by SilverTux** [comment]
Hi,

if you've downloaded the appimage of imagemagick (https://imagemagick.org/archive/binaries/magick) then you'll need some helperscripts I did something like this:

```
cat <<EOF >/usr/local/bin/convert
#!/usr/bin/env bash

set -euo pipefail

/usr/local/bin/magick convert $@
EOF
```

```
cat <<EOF >/usr/local/bin/import
#!/usr/bin/env bash

set -euo pipefail

/usr/local/bin/magick import $@
EOF
```

It assumes that you've downloaded your magick appimage binary to /usr/local/bin.
After this everything works properly.
