### ISSUE TITLE
dirname construct

### ISSUE THREAD

**Issue by AladW** [meskarune/i3lock-fancy#24]
This is unreliable, see:
http://mywiki.wooledge.org/BashFAQ/028

Also, why change directory? If it works as expected, the path is already stored in BASH_SOURCE. So you could replace
```
pushd $(dirname $0) > /dev/null
SCRIPTPATH=$(pwd)
popd > /dev/null
```
with
```
SCRIPTPATH=${BASH_SOURCE%/*}
```

**Comment by meskarune** [comment]
People wanted to download i3lock-fancy with git in their home and symlink to /usr/local/bin. If there is a good way of allowing this I'll totally make a change.

**Comment by AladW** [comment]
It seems the current pushd/popd code fails for me on that regard; I'll see what I can come up with.
