### ISSUE TITLE
Using this locker with dpms?

### ISSUE THREAD

**Issue by cj360** [meskarune/i3lock-fancy#32]
Hello, I've been using this lock setup with a manual keybind on openbox for a while but was wondering if the normal -d still works with this fork?

Ex:
xautolock -time 50 -locker "i3lock-fancy -d " -lockaftersleep &

So i3lock would blank & lock the screen after 50 minutes if that ^ formatting is right..

**Comment by joeythesaint** [comment]
This is from my Openbox autostart:

```
/usr/bin/xautolock -locker "/home/jjm/bin/lock -dg" -detectsleep -time 5
```

and it works like a charm.  `i3lock` starts up when it should and dpms kicks in later.  But do note that I'm managing my dpms setting through `xset`, not `xautolock`, so your needs may differ.

**Comment by cj360** [comment]
oh okay, but what if I just want i3lock to kick-in when xset does? Or does the lock program need to be specified and then the time to lock the screen?

**Comment by meskarune** [comment]
@cj360 I think if you want the -d option with i3lock-fancy the script would need to be edited and the line where i3lock is called would have -d option added. I use xautolock though with hot corners:

    xautolock -time 5 -locker '/usr/bin/i3lock-fancy' -detectsleep -corners 0-+0 &

I add that to my herbstluftwm autostart file and then the screen locks automatically after 5 min or will lock if I place the mouse cursor in the bottom left corner of the screen.

**Comment by AladW** [comment]
The -d option from i3lock was removed a while ago: https://github.com/i3/i3lock/blob/master/CHANGELOG#L1

This project isn't a fork of i3lock, but rather a wrapper script. So if you have i3lock or i3lock-color installed, it won't have -d either. If you want to run i3lock when the screensaver activates, and you use systemd, there's xss-lock.

**Comment by meskarune** [comment]
Thanks @AladW I think I'm going to close as it appears the solution is to use xss-lock or xautolock. @cj360 if you have more issues please reopen.
