### ISSUE TITLE
branch "dualmonitors" ImageMagick errors

### ISSUE THREAD

**Issue by sentriz** [meskarune/i3lock-fancy#34]
hello, when using the dualmonitors branch [i3lock-fancy-dualmonitors-git r81.1c32f7e-1](https://aur.archlinux.org/packages/i3lock-fancy-dualmonitors-git/), I get the following errors.

```
convert: unable to load font `-pointsize': Resource temporarily unavailable @ error/xwindow.c/XBestFont/828.
convert: unable to load font `-pointsize': Resource temporarily unavailable @ error/xwindow.c/XBestFont/828.
convert: unable to load font `-pointsize': Resource temporarily unavailable @ error/xwindow.c/XBestFont/828.
convert: unable to load font `-pointsize': Resource temporarily unavailable @ error/xwindow.c/XBestFont/828.
convert: unable to load font `-pointsize': Resource temporarily unavailable @ error/xwindow.c/XBestFont/828.
convert: unable to load font `-pointsize': Resource temporarily unavailable @ error/xwindow.c/XBestFont/828.
convert: unable to load font `-pointsize': Resource temporarily unavailable @ error/xwindow.c/XBestFont/828.
convert: unable to load font `-pointsize': Resource temporarily unavailable @ error/xwindow.c/XBestFont/828.
convert: unable to open image `26': No such file or directory @ error/blob.c/OpenBlob/2702.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
convert: unable to open image `26': No such file or directory @ error/blob.c/OpenBlob/2702.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
```

ImageMagick version:
```
Version: ImageMagick 6.9.3-10 Q16 x86_64 2016-05-05 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps rsvg tiff webp wmf x xml zlib
```

Thank you, 
Senan.

**Comment by meskarune** [comment]
Could you try the following commands and let me know what happens:

    convert -list fonts

    /usr/bin/i3lock-fancy -f sans

thanks!

**Comment by sentriz** [comment]
sure :)

`$ convert -list font`
http://termbin.com/uttv

`$ /usr/bin/i3lock-fancy -f sans`
works! but the text and lock icon on the _xrandr --primary_ monitor are blurred too.

**Comment by meskarune** [comment]
Thank you so much. One more thing, what does this give you?

    fc-match sans

I think there may be an issue with your font cache, but I'm not sure. If the regular script works for you I will compare the two branches to see if I am missing something.

**Comment by meskarune** [comment]
Oh, would you happen to have ghostscript installed?

**Comment by sentriz** [comment]
`$ fc-match sans`
Vera.ttf: "Bitstream Vera Sans" "Roman"

I do not have ghostscript installed. :)

**Comment by meskarune** [comment]
For future reference, the emojione-color-font pacakge is what caused the issue. Removing that package fixed the problem.

**Comment by sentriz** [comment]
@meskarune yes sorry, I should have mentioned that. (emojione-color-font)[https://aur.archlinux.org/packages/emojione-color-font/]

**Comment by mnzt** [comment]
I've also had the package `twemoji-color-font` cause these issues.

**Comment by meskarune** [comment]
Thanks @mnzt I'm sure that will help others in the future if they search for a similar issue!
