### ISSUE TITLE
text & lock blur on primary monitor.

### ISSUE THREAD

**Issue by sentriz** [meskarune/i3lock-fancy#35]
Hello, 
on the primary monitor defined with _xrandr --primary_, the text and lock are blurred.

![tmp zvpconynvp](https://cloud.githubusercontent.com/assets/6832539/15372038/5db8c796-1d36-11e6-82e3-22c675e8cdca.png)

Thank you, 
Senan.

**Comment by eugenelet** [comment]
Hey there, any update on this?

**Comment by f-breidenstein** [comment]
Can reproduce this bug. Same problem here.

**Comment by meskarune** [comment]
I don't have multiple monitors to test, so I'm not what to do to fix this...

I'm guess I need to change the order of the blur and icon/text compilation but I have no way of testing anything myself. My only computer is an under-powered netbook.

**Comment by VideahGams** [comment]
Removing `-blur 0x2` from line 74 appears to fix the issue(?)

**Comment by MagiCrazy** [comment]
I concur with @VideahGams 
I proposed a PR #56

**Comment by meskarune** [comment]
Thanks so much for figuring this out! I've pulled in the PR, I should have the AUR package updated soonish.
