### ISSUE TITLE
layout change

### ISSUE THREAD

**Issue by zsabay** [meskarune/i3lock-fancy#36]
Hello!
I use two layouts one is English, second is Cyrillic and I am not able to exit from lock-screen if the layout was Cyrillic. How do I change my keyboard layout to English before locking? I mean what lines do I need to add to the script to do it automatically. I tried just to add "setxkbmap -layout us" at the end of script but it doesn't seem to work. Any help would be appreciated!

**Comment by meskarune** [comment]
Honestly this sounds like it could be a bug with i3lock. You should be able to unlock with your password in any keyboard layout. Does your password have letters in english that aren't in the cyrillic keyboard?

**Comment by zsabay** [comment]
Sorry for bothering and keyboard layout switch actually works. I don't know why but I was not able to enter my password right like fifteen times :D
