### ISSUE TITLE
Ubuntu support?

### ISSUE THREAD

**Issue by mstaal** [meskarune/i3lock-fancy#42]
First of all: This extension looks really cool!

Do you know what it takes to make it run on Ubuntu? I have not yet made it to Arch, but I am currently trying to make a minimal Ubuntu install (that is, it is based on Ubuntu mini) with i3 as wm.

**Comment by meskarune** [comment]
You will need i3lock-color installed as well as any package listed in the dependancies, such as image magic and core utils like awk. Then you can clone the git repo and run the locker with "bash lock"

I use a program called xautolocker to automatically lock my screen after a delay. You could do that or set a hot key to run the lock program.

**Comment by meskarune** [comment]
I'm going to go ahead and close. Let me know if you are still having issues.
