### ISSUE TITLE
Run dialogs (rofi, dmenu) end up in the background image

### ISSUE THREAD

**Issue by Dinduks** [meskarune/i3lock-fancy#44]
Hi,

To lock my screen, I usually run Rofi and type `lock`. This unfortunately leads to the Rofi dialog being shown in the background image (like shown below).

![20160718_104940-1](https://cloud.githubusercontent.com/assets/504977/16910147/5432a734-4cd7-11e6-8ec4-98a486404e09.jpg)

Before discovering _i3lock-fancy_, I used a custom script that had `sleep $FEW_MILLIS` in the top of it to avoid that.

I suggest adding a feature in _i3lock-fancy_ to allow the user to specify a delay before taking the screenshot, in order to wait for the run dialog to close.
If you're okay with this, I can make a pull request.

Thank you.

**Comment by Dinduks** [comment]
Hi @meskarune. Do you want to merge this?

**Comment by meskarune** [comment]
Hello, I ended up adding on a custom screenshot command line option so you can do this:

    lock -- scrot -d 3

And it will set a delay before taking the shot. You can also use any other screenshot manager that you wish, including maim or gnome screenshot.
