### ISSUE TITLE
i3lock still has colors

### ISSUE THREAD

**Issue by errelion** [meskarune/i3lock-fancy#47]
hey there,

the lock essentialy works, but the ring still is displayed in green, and isnt grey as its supposed to be. what could cause this and how can i change it to be as grey as in the demo?

all i did was installing the lock like explained in the readme, didnt change any properties

btw, great lock, it really looks amazing!

**Comment by Arcaena** [comment]
From the [i3lock-color readme](https://github.com/Arcaena/i3lock-color):

> Example usage for colors:

>i3lock-color --insidevercolor=0000a0bf --insidewrongcolor=ff8000bf --insidecolor=ffffffbf --ringvercolor=0020ffff --ringwrongcolor=4040ffff --ringcolor=404090ff --textcolor=ffffffff --separatorcolor=aaaaaaff --keyhlcolor=30ccccff --bshlcolor=ff8000ff -r

You'll need to specify the specific colors you'll want to use

**Comment by errelion** [comment]
ah yes, thank you i found it

**Comment by errelion** [comment]
strange thing, i've changed the colors in /usr/locale/bin/lock but it does not have any effect on the i3lock.. everything else works, the blurry background etc, but the colors just dont differ from default

**Comment by Arcaena** [comment]
I dunno, [here](https://gist.github.com/Arcaena/b4218b3494d0cb318b27b947cf013927)'s my lock script. You'll prob need to change `i3lock-color` to `i3lock` since I'm bad and have been renaming the binary instead of fixing my scripts.

I might've broken something in the last commit yesterday so I'll take a glance in a bit and see if something broke

**Comment by meskarune** [comment]
It sounds like you are using i3lock instead of i3lock-color. You need to check what binary you have installed.

**Comment by meskarune** [comment]
Hello, if you are still having this issue, please reopen.
