### ISSUE TITLE
Create package in AUR

### ISSUE THREAD

**Issue by ylecuyer** [meskarune/i3lock-fancy#5]
Can you make this package available in the AUR ?

**Comment by meskarune** [comment]
Yeah, I'll work on an AUR package when I get some time later in the week :)

**Comment by burntcookie90** [comment]
https://github.com/burntcookie90/i3lock-fancy-PKGBUILD

I've created a PKGBUILD for my own use, you're welcome to push it to the aur if you'd like, or let me know if you want me to.

**Comment by ylecuyer** [comment]
:+1:

**Comment by meskarune** [comment]
Ok, a package is up in the AUR here: https://aur.archlinux.org/packages/i3lock-fancy-git/

I threw you on as a contributor @burntcookie90 thanks!

**Comment by burntcookie90** [comment]
Sounds good!
