### ISSUE TITLE
option to remove -n paramter

### ISSUE THREAD

**Issue by JJK96** [meskarune/i3lock-fancy#66]
I want to start this on suspend, but not after a specific time, I therefore do not use xautolock. 
Therefore I made a forking systemd service that runs before sleep.target and starts i3lock-fancy. 
This however required me to edit the script and remove the -n parameter. 

Could this become a command line option?

**Comment by AladW** [comment]
Duplicate of https://github.com/meskarune/i3lock-fancy/pull/60
