### ISSUE TITLE
systemd unit suspend issue

### ISSUE THREAD

**Issue by 2Belette** [meskarune/i3lock-fancy#67]
Hi,
First many thanks for this great tool I like it very much :)
I would like i3lock-fancy to start automatically before I suspend my computer, then when I wake up I have the great i3lock-fancy to ask me for a password.
I created this systemd unit : 
```
[Unit]
Description=Starts i3lock at suspend time
Before=sleep.target

[Service]
User=username
Type=forking
Environment=DISPLAY=:0
ExecStartPre=
ExecStart=/usr/bin/i3lock-fancy

[Install]
WantedBy=sleep.target
```
And it is working well but my computer never get to sleep. I need to type the password and then it goes to sleep!
Is there a way / parameter to pass to i3lock-fancy to handle this ?
Many thanks

**Comment by AladW** [comment]
Duplicate #39 #41 #60 #66
