### ISSUE TITLE
i3lock-fancy modprobe nvidia

### ISSUE THREAD

**Issue by Sudokamikaze** [meskarune/i3lock-fancy#69]
On my laptop i use bumblebee for my optimus nvidia and when i lock laptop, i3lock-fancy modprobe nvidia driver and after my videocard state is on, here is log

```
 ~ $ lock
modprobe: ERROR: could not insert 'nvidia': No such device
modprobe: ERROR: could not insert 'nvidia': No such device
```
and after 
```
Bumblebee status: Ready (3.2.1). X inactive. Discrete video card is on.
```

Distro is Archlinux, and sorry for my bad english

**Comment by AladW** [comment]
The script contains no modprobe commands, and otherwise no nvidia-specific commands. As such this is an upstream issue, but that should be diagnosed elsewhere (like the Arch forums).
