### ISSUE TITLE
Hide text in dualmonitors branch

### ISSUE THREAD

**Issue by danikron** [meskarune/i3lock-fancy#70]
Would it be possible to add an option to hide the text completely and just show the lock icon on the dualmonitors branch? As a temporary workaround for the text not being completely centered.

**Comment by AladW** [comment]
You know what they say about temporary workarounds... though having an option to not display text might otherwise be useful.

**Comment by danikron** [comment]
Yeah, okay, let's call this a feature request then. :)

**Comment by meskarune** [comment]
You can already do this with

    lock -t ""

**Comment by AladW** [comment]
Work to merge dual-monitors to master is done in #87. Closing as duplicate
