### ISSUE TITLE
Script shows a black background when autostarted with i3

### ISSUE THREAD

**Issue by ReekyMarko** [meskarune/i3lock-fancy#74]
Works fine otherwise, but when I add i3lock-fancy to the startup files in i3config, I get only a black background.

Here's how I start it:
exec --no-startup-id i3lock-fancy

One thing to note that if I change the command to exec_always and restart i3 it works fine. Seems that the utility to create the screenshot might not be ready when it's only started on first startup.

**Comment by chrjguill** [comment]
It could be that the screenshot is taken before the compositor starts, or before anything is rendered. You may want to run i3lock with a static image if you run it at i3 init.

**Comment by AladW** [comment]
No indication this is related to the script.
