### ISSUE TITLE
Arch build failure

### ISSUE THREAD

**Issue by zogthealien** [meskarune/i3lock-fancy#80]
[redacted@redacted-arch i3lock-fancy-git]$ makepkg -si
==> Making package: i3lock-fancy-git r125.e7eb9e7-1 (Wed May 24 15:35:33 IST 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating i3lock-fancy git repo...
Fetching origin
  -> Found package.patch
==> Validating source files with md5sums...
    i3lock-fancy ... Skipped
    package.patch ... Passed
==> Extracting sources...
  -> Creating working copy of i3lock-fancy git repo...
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
patching file /home/redacted/i3lock-fancy-git/src/i3lock-fancy/lock
Hunk #1 FAILED at 79.
1 out of 1 hunk FAILED -- saving rejects to file /home/redacted/i3lock-fancy-git/src/i3lock-fancy/lock.rej
==> ERROR: A failure occurred in build().
    Aborting...

Arch, fully up to date system. What gives?

**Comment by AladW** [comment]
We probably need a makefile so we don't need patches that are always out of date.

**Comment by zogthealien** [comment]
So there's no way to install this until fixed?

**Comment by AladW** [comment]
Install it by hand, see the installation section in the readme.
