### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by ng-0** [meskarune/i3lock-fancy#81]
As found out in #80 a Makefile would make sense.
I can try my hands on a Makefile, I'm patching many things by hand now to include references to store items in Guix.

**Comment by meskarune** [comment]
I think having a makefile is a great idea. I have never written one before though. If you want to try making one I would def appreciate it.

**Comment by AladW** [comment]
Basic makefile you could adapt: https://github.com/AladW/aurutils/blob/master/Makefile

**Comment by meskarune** [comment]
I've added a make file to the repo and it appears to be working. I will go ahead and close this issue. Thanks y'all! <3
