### ISSUE TITLE
turn executables into variables

### ISSUE THREAD

**Issue by ng-0** [meskarune/i3lock-fancy#82]
if you could make 'import' and other executables variables defined at the beginning of the script, this would spare myself keeping up to date with changes in the script and just patch thevariables. Right now I'm patching every occurence of binaries to store-paths so that the references in Guix aren't garbage collected.

**Comment by AladW** [comment]
I don't understand the problematic. Do you want to define _every_ executable (awk, convert, etc.) at the top of the script? Or do you just want to move up https://github.com/meskarune/i3lock-fancy/blob/master/lock#L10-L18 up to L2?
