### ISSUE TITLE
What happened to the AUR package ?

### ISSUE THREAD

**Issue by TheRizzen** [meskarune/i3lock-fancy#92]
I've just seen you disown the package i3lock-fancy in the AUR and created another package named "i3lock-fancy-dualmonitors-git". What is the reason behind this change ?

**Comment by patrick96** [comment]
I don't know why the package got removed but the dualmonitors package has existed for ages and is based on the dualmonitors branch in this repo.
There is a [`i3lock-fancy-git`](https://aur.archlinux.org/packages/i3lock-fancy-git/) package but it fails to build, I think [this PKGBUILD](https://gist.github.com/octomike/741ae9d22e1fb47c470903992b8193d7) is your best bet, if you want an up to date package without having to write the PKGBUILD yourself.
