### ISSUE TITLE
Does not work -- exits silently

### ISSUE THREAD

**Issue by tastyminerals** [meskarune/i3lock-fancy#98]
I am trying to replace the script I was using for some time:
```bash
#!/bin/bash
i3lock -i <(import -window root - | convert -blur -2x5 - png:-)
```

The code above stopped blurring the background, the background becomes completely white so I decided to give this repo a try. Unfortunately it does not work for me as well. When I try `lock` or `i3lock-fancy` it just silently exits. Is there a way to debug what's going on?

**Comment by AladW** [comment]
`convert --version`

**Comment by tastyminerals** [comment]
```
Version: ImageMagick 6.9.9-21 Q16 x86_64 2017-10-31 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
```

**Comment by AladW** [comment]
Update imagemagick to 6.9.9-23.
